### ISSUE TITLE
db password option reverted?

### ISSUE THREAD

**Issue by jafow** [handshake/pg2kinesis#17]
Hello 👋 
Thanks for making this tool it's great!

Looks like the db password option was reverted in [3208de3](https://github.com/handshake/pg2kinesis/commit/3208de3fd0274978f3f6da18e4afb0cde04648f8), and just wondering why. 

It seems like `sslmode` option used here instead, might depend on a `DSN` environment variable that psycopg2 reads on connect. 

if that's the case, would you accept a PR to add an example of this pattern in the README.md? It threw me for a second.
Thanks

**Comment by surbas** [comment]
Hi 👋

Glad it has been of use to you!

It has been a while... but I think we removed it cause we didn't feel it was a safe way of authenticating in real production. 

A PR with an example would be great! 

Best
Shon

**Comment by jafow** [comment]
Thanks for your answer :+1:
